app = "aa-syncban"
primary_region = 'iad'

[build]
image = "registry.hub.docker.com/rocicorp/zero:0.18.2025040300"

[http_service]
internal_port = 4848
force_https = true
auto_stop_machines = 'off'
min_machines_running = 1

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/"

[[vm]]
size = 'performance-16x'

[mounts]
source = "sqlite_db"
destination = "/data"

[env]
JWT_SECRET="supersecret"
ZERO_LOG_LEVEL="debug"
ZERO_PUSH_URL="https://syncban.vercel.app/api/zero/push"
ZERO_REPLICA_FILE="/tmp/zero.db"
ZERO_UPSTREAM_DB=""
