/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ZeroRouteImport } from './routes/zero.route'
import { Route as PowersyncRouteImport } from './routes/powersync.route'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ZeroRouteRoute = ZeroRouteImport.update({
  id: '/zero',
  path: '/zero',
  getParentRoute: () => rootRoute,
} as any)

const PowersyncRouteRoute = PowersyncRouteImport.update({
  id: '/powersync',
  path: '/powersync',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/powersync': {
      id: '/powersync'
      path: '/powersync'
      fullPath: '/powersync'
      preLoaderRoute: typeof PowersyncRouteImport
      parentRoute: typeof rootRoute
    }
    '/zero': {
      id: '/zero'
      path: '/zero'
      fullPath: '/zero'
      preLoaderRoute: typeof ZeroRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/powersync': typeof PowersyncRouteRoute
  '/zero': typeof ZeroRouteRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/powersync': typeof PowersyncRouteRoute
  '/zero': typeof ZeroRouteRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/powersync': typeof PowersyncRouteRoute
  '/zero': typeof ZeroRouteRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/powersync' | '/zero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/powersync' | '/zero'
  id: '__root__' | '/' | '/powersync' | '/zero'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PowersyncRouteRoute: typeof PowersyncRouteRoute
  ZeroRouteRoute: typeof ZeroRouteRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PowersyncRouteRoute: PowersyncRouteRoute,
  ZeroRouteRoute: ZeroRouteRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/powersync",
        "/zero"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/powersync": {
      "filePath": "powersync.route.tsx"
    },
    "/zero": {
      "filePath": "zero.route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
